### ISSUE TITLE
Error: The "immutable" directive accepts as argument a variable name 

### ISSUE THREAD

**Issue by jigargandhi** [mgechev/angular-immutable#10]
The error is occurring where we specify `ng-controller="name as alias"`

```
  <div ng-controller="ctrl as vm">
      {{vm.data}}
      <ul>
        <li immutable="vm.list" ng-repeat="items in vm.list" ng-bind="items">
          {{items}}
        </li>
        </ul>
      </ul>
    </div>
```

Sample http://plnkr.co/edit/Fo1koZvxemrQYEsns9w0

**Update 1**: You will need to loop through string provided for the attribute to reach the correct reference.

**Comment by mgechev** [comment]
@jigargandhi test against `nested-props` branch, it should work now. Here's the PR https://github.com/mgechev/angular-immutable/pull/11

**Comment by jigargandhi** [comment]
:+1: nested members work with the `nested-props` branch

**Comment by rayronvictor** [comment]
@mgechev can you update the npm version with PR #11?

**Comment by mgechev** [comment]
Done.

**Comment by rayronvictor** [comment]
Thanks!
