### ISSUE TITLE
bad sourceURL

### ISSUE THREAD

**Issue by loganfreeman** [mgechev/angular-immutable#7]
bad sourceURL

//# sourceURL=/Users/soocheng/Documents/angular-immutable/lib/immutable.js

**Comment by nathanmarks** [comment]
Yeah, @mgechev can you please make the `/lib` folder available when installing via NPM so we can require it ourselves and not have stack traces looking like this:

(**This is not a path on my machine!**)

```
at Object.<anonymous> (/Users/soocheng/Documents/angular-immutable/lib/immutable.js:74316:11)
```

It also pops up a warning from webpack every single page load in the console:

![image](https://cloud.githubusercontent.com/assets/4420103/11565246/13de9934-99ab-11e5-89e4-a22ab2e78317.png)

**Comment by mgechev** [comment]
Fixed. The entire library was broken since https://github.com/mgechev/angular-immutable/commit/c4ddc0867fd4f204d7ca4bc6aa0ab50736d3cd2c

**Comment by nathanmarks** [comment]
@mgechev Thanks!
