### ISSUE TITLE
controllerAs syntax support

### ISSUE THREAD

**Issue by char0n** [mgechev/angular-immutable#9]
Hi,

There seems to be no support for controllerAs syntax. It there any planned support for controllerAs syntax ?

I have been experimenting with your directive and these 2 functions, but with any solid result yet.

``` javascript
function getPropertyByPath(obj, path) {
  var i, j, parent, ref;
  path = path.split('.');
  parent = obj;
  if (path.length > 1) {
    for (i = j = 0, ref = path.length - 2; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
      parent = parent[path[i]];
    }
  }
  return parent != null ? parent[path[path.length - 1]] : void 0;
}

function setPropertyByPath(obj, path, value) {
  var i, j, name, parent, ref;
  path = path.split('.');
  parent = obj;
  if (path.length > 1) {
    for (i = j = 0, ref = path.length - 2; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
      parent = (parent[name = path[i]] || (parent[name] = {}));
    }
  }
  return parent[path[path.length - 1]] = value;
}
```

**Comment by char0n** [comment]
Your documentation also says that this is possible:

``` html
<li immutable="data.nestedList" ng-repeat="item in immutables track by $index" ng-bind="item"></li>
```

But from the source code I can clearly see that it is not.

``` javascript
if (!/^[a-zA-Z0-9_$]+$/.test(immutable)) {
```

Am I missing something here ?

**Comment by mgechev** [comment]
@char0n the documentation is out-of-date. I'll update not now.

At this point I don't have plans to implement `controllerAs` syntax since I'm mostly focused on [Angular 2](http://blog.mgechev.com/2015/03/02/immutability-in-angularjs-immutablejs/#comment-2441570721).
